# Enable AndroidX
android.useAndroidX=true

# Enable Jetifier (safe even if not needed)
android.enableJetifier=true

# Kotlin
kotlin.code.style=official

# Gradle
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# Android
android.nonTransitiveRClass=true
android.nonFinalResIds=false

# Incremental compilation
kotlin.incremental=true

# Configuration cache
org.gradle.configuration-cache=true

# Parallel build
org.gradle.parallel=true

# Caching
org.gradle.caching=true